development:
  couchdb: 'http://couchdb:5984'
  couchdb_url: 'http://localhost:5984'
  elasticsearch: 'http://elasticsearch:9200'
  elasticsearch_url: 'http://localhost:9200'
  connect: 'http://connect:8080'
  connect_url: 'http://localhost:8080'
  base: ""
test:
  couchdb: 'http://couchdb:5984'
  couchdb_url: 'http://localhost:5984'
  elasticsearch: 'http://elasticsearch:9200'
  elasticsearch_url: 'http://localhost:9200'
  connect: 'http://connect:8080'
  connect_url: 'http://localhost:8080'
  base: ""
production:
  couchdb: 'http://jb048:5984'
  couchdb_url: 'http://$HOST/couchdb'
  elasticsearch: 'http://jb048:9200'
  elasticsearch_url: 'http://$HOST/elasticsearch'
  connect: 'http://jb048/connect'
  connect_url: 'http://$HOST/connect'
  base: "/migrator"
production:
  couchdb: 'http://jb049:5984'
  couchdb_url: 'http://$HOST/couchdb'
  elasticsearch: 'http://jb049:9200'
  elasticsearch_url: 'http://$HOST/elasticsearch'
  connect: 'http://jb049/connect'
  connect_url: 'http://$HOST/connect'
  base: "/migrator"
