development:
  couchdb: 'http://192.168.50.21:5984'
  elasticsearch: 'http://192.168.50.21:9200'
  base: ""
test:
  couchdb: 'http://192.168.50.21:5984'
  elasticsearch: 'http://192.168.50.21:9200'
  base: ""
production:
  couchdb: 'http://cncflora.jbrj.gov.br/couchdb'
  elasticsearch: 'http://cncflora.jbrj.gov.br/elasticsearch'
  base: "/migrator"
